//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1_Re
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryCheckingTask
    {
        public InventoryCheckingTask()
        {
            this.TaskDetail = new HashSet<TaskDetail>();
        }
    
        public int Id { get; set; }
        public string TaskName { get; set; }
        public int WarehouseId { get; set; }
        public int TaskTypeId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int StatusId { get; set; }
    
        public virtual TaskStatus TaskStatus { get; set; }
        public virtual TaskType TaskType { get; set; }
        public virtual ICollection<TaskDetail> TaskDetail { get; set; }
    }
}
