//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1_Re
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class S1Entities : DbContext
    {
        public S1Entities()
            : base("name=S1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<InventoryCheckingTask> InventoryCheckingTask { get; set; }
        public DbSet<Part> Part { get; set; }
        public DbSet<PartCategory> PartCategory { get; set; }
        public DbSet<PartStorage> PartStorage { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<Staff> Staff { get; set; }
        public DbSet<TaskDetail> TaskDetail { get; set; }
        public DbSet<TaskStatus> TaskStatus { get; set; }
        public DbSet<TaskType> TaskType { get; set; }
        public DbSet<Warehouse> Warehouse { get; set; }
        public DbSet<Zone> Zone { get; set; }
    }
}
