//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1_Re
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public Part()
        {
            this.TaskDetail = new HashSet<TaskDetail>();
            this.PartStorage = new HashSet<PartStorage>();
        }
    
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public string Specification { get; set; }
        public int MinInventory { get; set; }
        public int MaxInventory { get; set; }
    
        public virtual ICollection<TaskDetail> TaskDetail { get; set; }
        public virtual PartCategory PartCategory { get; set; }
        public virtual ICollection<PartStorage> PartStorage { get; set; }
    }
}
